# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-14 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.TextField(default='tes semua'),
            preserve_default=False,
        ),
    ]
