# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-14 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('publish_artikel', 'Can publish artikel'),)},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='published',
        ),
    ]
