# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-15 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200114_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
