# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-16 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={},
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='published',
        ),
    ]
