# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-16 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200116_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='published',
            field=models.DateTimeField(null=True),
        ),
    ]
